### ISSUE TITLE
Add it in mplug script directory 

### ISSUE THREAD

**Issue by z8512** [alifarazz/mpv-zenity-open-files#1]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by alifarazz** [comment]
I don't use mplug, so it's up to someone who uses it to do this.
PRs are welcome 😅
